# Generated by Django 4.0.2 on 2025-03-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='date',
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='amount_paid',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='tooth_number',
            field=models.CharField(choices=[('t1', 't1'), ('t2', 't2'), ('t3', 't3'), ('t4', 't4'), ('t5', 't5'), ('t6', 't6'), ('t7', 't7'), ('t8', 't8'), ('t9', 't9'), ('t10', 't10'), ('t11', 't11'), ('t12', 't12'), ('t13', 't13'), ('t14', 't14'), ('t15', 't15'), ('t16', 't16'), ('t17', 't17'), ('t18', 't18'), ('t19', 't19'), ('t20', 't20'), ('t21', 't21'), ('t22', 't22'), ('t23', 't23'), ('t24', 't24'), ('t25', 't25'), ('t26', 't26'), ('t27', 't27'), ('t28', 't28'), ('t29', 't29'), ('t30', 't30'), ('t31', 't31'), ('t32', 't32')], max_length=3),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('temporary_filling', 'حشوة موقتة'), ('permanent_filling', 'حشوة دائمة'), ('extraction', 'قلع'), ('implant', 'زراعة')], max_length=20),
        ),
    ]
