# Generated by Django 4.0.2 on 2025-03-28 23:57

import clinic.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_treatment_date_treatment_treatment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clinic.models.patient_image_upload_path),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
