# Generated by Django 4.0.2 on 2025-03-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_treatment_image_alter_treatment_treatment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('حشوه موقتة', 'حشوة موقتة'), ('حشوه دائمه', 'حشوة دائمة'), ('قلع', 'قلع'), ('زراعة', 'زراعة'), ('جذر', 'جذر')], max_length=20),
        ),
    ]
