# Generated by Django 4.0.2 on 2025-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_treatment_note_alter_treatment_tooth_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
