# Generated by Django 4.0.2 on 2025-04-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_treatment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='first_installment',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
