# Generated by Django 4.0.2 on 2025-04-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_treatment_first_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='remaining_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
