# Generated by Django 4.0.2 on 2025-04-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_treatment_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='amount_paid',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='first_installment',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='remaining_amount',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
