# Generated by Django 5.2.5 on 2025-08-10 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0011_alter_treatment_amount_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="amount_paid",
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="first_installment",
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Sunday", "الأحد"),
                            ("Monday", "الإثنين"),
                            ("Tuesday", "الثلاثاء"),
                            ("Wednesday", "الأربعاء"),
                            ("Thursday", "الخميس"),
                            ("Friday", "الجمعة"),
                            ("Saturday", "السبت"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time", models.TimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "time"],
            },
        ),
    ]
