# Generated by Django 5.2.5 on 2025-08-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0012_alter_treatment_amount_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
