# Generated by Django 5.2.5 on 2025-08-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0013_remove_appointment_patient_appointment_patient_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={},
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="day",
        ),
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
